### ISSUE TITLE
HW 5: covariates

### ISSUE THREAD

**Issue by mdscheuerell** [eric-ward/safs-timeseries#10]
Hi there,

I wanted to jump in and mention that in this case I do NOT recommend transforming (eg, z-score) your covariates in the DLMs you fit for this week's homework. I can talk about the reasons in class on Tues.

Mark

**Comment by mfeddern** [comment]
Follow up: I am working on problem 2 and having a hard time with what my Z matrix should be. For problem 1 I set it as an identity matrix since we were only fitting alpha, and I understand what to do when I have covariates, I guess I am having a hard time conceptualizing what it should be with two parameters (m). I could be going down the wrong path completely...


Z = array(NA, c(1, m, TT))  
Z[1, 1, ] = rep(1, TT) 
Z[1, 2, ] = ???

**Comment by mdscheuerell** [comment]
Hi @mfeddern. Recall that in a DLM regr with stochastic intercept and slope, is often written as

y_t = X_t^T theta_t + e_t

with X_t^T = [1 x_t] and theta = [alpha beta]^T ([see here](https://nwfsc-timeseries.github.io/atsa/Lectures/Week%205/lec_09_intro_to_DLMs.html#27))

In `MARSS()` notation, we instead write the model as

y_t = Z_t x_t + v_t

If you substitute Z_t for X_t^T into the first equation, can you see what the second dim of `Z[1, 2, ]` should be?

**Comment by mfeddern** [comment]
So Z_t should be [1, x_t] and the second dimension should be x_t.  I am still confused how to code that without a covariate? 

For the lab example we used upwelling as our ft (instead of xt) and that was our second dimension was our z-score transformed covariate. So I understand how to do the next one I think I am just missing something conceptually still to get this intermediate model, I am probably over thinking it.
