### ISSUE TITLE
Question re HW #2 Q 1.3

### ISSUE THREAD

**Issue by eeholmes** [eric-ward/safs-timeseries#5]
for question 1.3 in HW #2.  It was confusing that you said m_t = 0.  When we do decompose(pDat) the trend panel is not zero.  In't that 2nd panel m_t so definitely not zero?

**Comment by mdscheuerell** [comment]
OK, here are a few hints about HW#2.

Recall that our general approach to model building is to remove any systematic trends and seasonal effects from a time series, which we hope will leave us with stationary residuals (_i.e._, {e_t}). If you call `decompose` on the raw data you will, in fact, see that the "trend" component is non-zero, but the Q indicates that you should really be examining a transformed version of the raw data.

That issue aside, recall that `decompose` is using some form of linear filter to estimate a trend. If we can safely assume that the filter should return 0 for all t because the manufacturer assures you it to be true, then what appears to be a trend might instead be part of another term in the decomposition model. If so, then perhaps you can't use `decompose` and you'll instead need to think about 1) the specific eqn for classical decomposition, and 2) the approach outlined in Sec 1.2 of the lab handout.

How might your approach change if m_t = 0 for all t?

**Comment by ericward-noaa** [comment]
On Thursday, the way that Eli and I interpreted this was to
1) log transform the data
2) concert to ts object with frequency = 24
3) apply decompose to extract the seasonal component
4) assume m_t = 0, and subtract off the seasonal component from the raw data

**Comment by mdscheuerell** [comment]
Yes, that will work, but it's less straightforward.
